CREATE TABLE documents (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       original_filename VARCHAR(255) NOT NULL,
       content_type VARCHAR(100) NOT NULL,
       status VARCHAR(30) NOT NULL,
       source_type VARCHAR(30) NOT NULL,
       extracted_text_length INTEGER,
       failure_reason TEXT,
       created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
       updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

       CONSTRAINT chk_documents_status
           CHECK (status IN ('UPLOADED', 'PROCESSING', 'READY', 'FAILED')),

       CONSTRAINT chk_documents_source_type
           CHECK (source_type IN ('PDF', 'TXT', 'MD'))
);