CREATE TABLE document_chunks (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     document_id BIGINT NOT NULL,
     chunk_index INTEGER NOT NULL,
     page_number INTEGER,
     content TEXT NOT NULL,
     content_hash VARCHAR(64) NOT NULL,
     embedding vector(768),
     token_estimate INTEGER,
     created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

     CONSTRAINT fk_document_chunks_document
         FOREIGN KEY (document_id)
             REFERENCES documents (id)
             ON DELETE CASCADE,

     CONSTRAINT uq_document_chunks_document_chunk_index
         UNIQUE (document_id, chunk_index),

     CONSTRAINT uq_document_chunks_document_content_hash
         UNIQUE (document_id, content_hash)
);