CREATE TABLE question_answer_runs (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      document_id BIGINT NOT NULL,
      question TEXT NOT NULL,
      answer TEXT,
      answer_status VARCHAR(40) NOT NULL,
      model_name VARCHAR(100),
      embedding_model_name VARCHAR(100),
      top_k INTEGER NOT NULL,
      raw_prompt TEXT,
      raw_model_output TEXT,
      failure_reason TEXT,
      created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_question_answer_runs_document
          FOREIGN KEY (document_id)
              REFERENCES documents (id)
              ON DELETE CASCADE,

      CONSTRAINT chk_question_answer_runs_answer_status
          CHECK (answer_status IN ('ANSWERED', 'INSUFFICIENT_CONTEXT', 'FAILED')),

      CONSTRAINT chk_question_answer_runs_top_k
          CHECK (top_k > 0)
);