CREATE TABLE retrieved_chunks (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      qa_run_id BIGINT NOT NULL,
      document_chunk_id BIGINT,
      rank INTEGER NOT NULL,
      similarity_score DOUBLE PRECISION NOT NULL,
      content_snapshot TEXT NOT NULL,
      page_number_snapshot INTEGER,
      created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_retrieved_chunks_qa_run
          FOREIGN KEY (qa_run_id)
              REFERENCES question_answer_runs (id)
              ON DELETE CASCADE,

      CONSTRAINT fk_retrieved_chunks_document_chunk
          FOREIGN KEY (document_chunk_id)
              REFERENCES document_chunks (id)
              ON DELETE SET NULL,

      CONSTRAINT uq_retrieved_chunks_qa_run_rank
          UNIQUE (qa_run_id, rank),

      CONSTRAINT chk_retrieved_chunks_rank
          CHECK (rank > 0)
);